// https://rfitz.io/blog/tailwind-with-react
export const NavbarStyle = {
    NavbarNav: `bg-gray-800`,
    SrOly: `sr-only`,
    MainWapper: `px-2 mx-auto max-w-7xl sm:px-6 lg:px-8`,
    NavBox: `relative flex items-center justify-between h-16`,
    MobileButtonBox: `absolute inset-y-0 left-0 flex items-center sm:hidden`,
    MobileButton: `inline-flex items-center justify-center p-2 text-gray-400 rounded-md hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white`,
    LogoMenuBox: `flex items-center justify-center flex-1 sm:items-stretch sm:justify-start`,
    LogoBox: `flex items-center flex-shrink-0`,
    MenuBox: `hidden sm:block sm:ml-6`,
    MobileLogoImage: `block w-auto h-8 lg:hidden`,
    LogoImage: `hidden w-auto h-8 lg:block`,
    TextLogoImage: `hidden w-auto h-8 lg:block`,
    TextMenuBox: `flex space-x-4`,
    ActiveTextMenu: `px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white`,
    TextMenu: `px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white`,
    LeftButtonBox: `absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0`,
    NotiButton: `p-1 text-gray-400 bg-gray-800 rounded-full hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white`,
    PHPButtonBox: `relative ml-3`,
    PHPButton: `flex text-sm bg-gray-800 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white`,
    MobileMenuBox: `hidden sm:hidden`,
    MobileMenu: `px-2 pt-2 pb-3 space-y-1`,
    MobileActiveMenu: `block px-3 py-2 text-base font-medium text-white bg-gray-900 rounded-md`,
    MobileNonActiveMenu: `block px-3 py-2 text-base font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white`,
};
